name: Generate docs

on:
  push:
    branches: ["*"]
    paths:
      - README.md
      - .github/workflows/panvimdoc.yml

jobs:
  panvimdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: nvimcord
          version: NVIM v0.10.0
          treesitter: true
          shiftheadinglevelby: -1
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto generate docs
