name: Generate docs

on:
  push:
    branches: [master]
    paths:
      - README.md
      - .github/workflows/panvimdoc.yml

jobs:
  panvimdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kdheepak/panvimdoc@v3.0.0
        with:
          vimdoc: nvimcord
          version: NVIM v0.8.0
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto generate docs
